### ISSUE TITLE
Help Wanted: Add `format()`, `printf()`, and `printlnf()` functions.

### ISSUE THREAD

**Issue by MaiTheLord** [MaiTheLord/BetterOTA#5]
### Summary:
We're currently missing those functions.
The greatest challenge is to implement the `format()` function.

In case something is not clear, the `format()` function should take multiple strings as parameters, and replace `%s`s and `%d`s in the first string with the other strings, by order, then return the formatted string, similarly to what Java's `String.format()` method does.

The following might prove useful:
- a variadic function
- `snprintf()`
---
### Guidelines to implementing `format()`:
- declare it in `BetterOTA.h` and define it in `BetterOTA.cpp`
- its return type should be a `String`
### Guidelines to implementing `printf()` and `printlnf()`:
- declare them is public members of `OTATerminalClass`, in `BetterOTA.h`
- they should return `void`
- define them in `BetterOTA.cpp`, like this:
```cpp
void OTATerminalClass::printf() {
    terminal->outgoing += format();
}

void OTATerminalClass::printlnf() {
    terminal->outgoing += format() + "\n";
}
```

**Comment by radekrudak** [comment]
So it might be(and probably is) stupid question but by "should take multiple strings as parameters, and replace %ss and %ds in the first string with the other strings",
you mean, "Should return formated string "
or it should take string with  %ss and %ds by reference and format string directly. 
Or both with some function overloading.

**Comment by MaiTheLord** [comment]
> you mean, "Should return formated string "
or it should take string with %ss and %ds by reference and format string directly.

It should return the formatted string,

**Comment by radekrudak** [comment]
> > you mean, "Should return formated string "
> > or it should take string with %ss and %ds by reference and format string directly.
> 
> It should return the formatted string.

Ok it seems simple enough if no one else did this i will try to do this issue

**Comment by MaiTheLord** [comment]
Go for it.

**Comment by radekrudak** [comment]
So how many types of arguments should format() take ? 
only strings and integers with %s %d or everything that C's printf provides ?

**Comment by radekrudak** [comment]
Also since i don't have ESP i will need help with testing (but for now i'm able to test on my desktop with std::string with is different from aruino's String but similar enough)

**Comment by MaiTheLord** [comment]
No problem, I could test it for you.

**Comment by MaiTheLord** [comment]
> So how many types of arguments should format() take ? only strings and integers with %s %d or everything that C's printf accepts ?

I think it should accept every type that can be stringified.

**Comment by radekrudak** [comment]
> No problem, I could test it for you.

OK, sending code to test trough pull request would be fine or should i posting it here ?

**Comment by MaiTheLord** [comment]
pull request is fine. just mention that its solving this issue.
